logging:
  level:
    net.shyshkin: debug
server:
  port: 8091
spring:
  application:
    name: product-service

  data:
    mongodb:
      database: productdb
#      username: username
#      password: password
#      host: localhost
#      port: 27017
